name : CI Pipline 

on :
  push:
    braches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
     - name: Checkout Code
        uses: actions/checkout@v3

      - name: Node install
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependenci
        runs: npm i


