name : CI Pipline 

on :
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependenci
        run: npm i

      - name: Start Application
         run: node index.js


